name: release-please
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    name: create-or-update-release-pr
    runs-on: ubuntu-24.04
    steps:
      - name: run-release-please
        uses: googleapis/release-please-action@v4
        with:
          manifest-file: .release-please-manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
